apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: nekobox

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- pv.yaml

generatorOptions:
  disableNameSuffixHash: true
images:
- name: nekobox
  newName: registry.cn-hangzhou.aliyuncs.com/n3ko/nekobox
  newTag: 20221125-043705
