apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-nekobox
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nas-nekobox
  storageClassName: lightcube-nekobox
  volumeMode: Filesystem
