apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-nekobox
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nas-e79173fc-87a5-417b-aa6f-1594b137a446
  storageClassName: lightcube-nekobox
  volumeMode: Filesystem
