kind: Deployment
apiVersion: apps/v1
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: busybox:latest
          name: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            - name: root
              mountPath: /home/fs
          command: ["sleep"]
          args: ["infinity"]
      tolerations:
        - key: "app"
          value: "nekobox"
          operator: "Equal"
          effect: "NoSchedule"
      terminationGracePeriodSeconds: 60
      volumes:
        - name: root
          persistentVolumeClaim:
            claimName: nas-root
        - name: timezone
          hostPath: 
            path: /usr/share/zoneinfo/Asia/Shanghai
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%