apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-root
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nas-root
  storageClassName: lightcube-root
  volumeMode: Filesystem
