apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 14.4.0
    helm:
      values: |
        global:
          storageClass: lightcube-postgres
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
